# Demo created with https://github.com/charmbracelet/vhs
Output media/demo.gif

Set FontSize 18
Set Width 1200
Set Height 600

Type "python ./tatoeba-sentences.py"
Sleep 500ms
Enter
Sleep 2s
Type "幫"
Enter
Sleep 3s

Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 1s
Enter

Sleep 1s
Type "貓"
Enter
Sleep 3s

Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 1s
Enter

Sleep 1s
Enter

Sleep 8s
